### ISSUE TITLE
Cannot reproduce the results on cityscapes dataset

### ISSUE THREAD

**Issue by Grace625** [AutoAILab/DynamicDepth#6]
Thanks for your excellent work! 

I downloaded the pre-trained model you provided in https://drive.google.com/file/d/1k3-7nki-v6k111wBZ-7pQNVU8QU7Nemx/view, and I ran the original code of evaluate_depth.py provided by ManyDepth project, using your pre-trained model as 'load_weights_folder'. I got the following results, which are different from the results you provided in the paper:
```
Scaling ratios | med: 57.521 | std: 0.105

   abs_rel |   sq_rel |     rmse | rmse_log |       a1 |       a2 |       a3 | 
&   0.105  &   1.006  &   5.996  &   0.160  &   0.888  &   0.972  &   0.991  \\
```

Looking forward to your reply. Thank you!

**Comment by fengziyue** [comment]
Hi @Grace625 : 

Thank you for your interest!

The `evaluate_depth.py` does not implement our DOMD module in the inference, so the result will be worse. However, it is still much better than the original Manydepth (AbsRel 0.127), which shows the model benefits a lot from our DOMD module during training.

You can use the `val()` function in the `trainer.py`, which will perform an evaluation before training starts if the `load_weights_folder` is provided:
`python -m dynamicdepth.train --load_weights_folder PATH_TO_PRETRAINED_MODEL`
you will get:
![image](https://user-images.githubusercontent.com/21237230/185182867-893ba187-b82c-40d0-a820-7f4d7c0490a3.png)

The original pre-trained model is lost due to maintenance on the cluster I used. The model I provided is reproduced last week, I will try to improve and update it in the near future.

**Comment by Grace625** [comment]
I got it. Thank you!
