### ISSUE TITLE
Dynamic object masks for KITTI dataset

### ISSUE THREAD

**Issue by Beniko95J** [AutoAILab/DynamicDepth#9]
Hi, I also want to reproduce your results on KITTI dataset. Would you please share the dynamic object masks for KITTI dataset also?

Hope for your reply, thanks!

**Comment by fengziyue** [comment]
Hi @Beniko95J : 

Thank you so much for your interest!

The original data was lost and I’m not planning to regenerate on the KITTI dataset very soon since it contains too few moving objects (most of the cars are parked), so our improvement is not very significant. You can try on the cityscapes dataset!
